### ISSUE TITLE
How to add individual flags documentation missing

### ISSUE THREAD

**Issue by xihh87** [danyk20/ctfd-personal_challenge-plugin#1]
When installing personal_challenge plugin, the `Create Flag` option at the `/admin/challenges/<chal>` gives the option to add an individual flag, but that option says:

> Do not create any individual flags from here!!!
> Only generate app can add new individual flags for personal challenge!

![Cannot add individual flags on flag edition](https://user-images.githubusercontent.com/16003955/215819008-f55b3c65-7b45-483a-a7c2-8f05f1db83c1.png)

On challenge creation, there is a warning saying that the challenge only works with individual flags, but there is no indication on how to do that.

![Cannot add individual flags on challenge creation](https://user-images.githubusercontent.com/16003955/215818985-e34d9836-dbb6-4fcf-bdbc-5d0f388d9ac9.png)

The only way I found to add individual keys is to query the database directly and add:

- The flag on the `flags` table
- A record on `individual_flag` table to associate the table to the user.

Where is the "generate app" which can add individual flags, and how does it work?

**Comment by xihh87** [comment]
I found that [the recommended app to add the challenges](https://gitlab.fi.muni.cz/kypolab/theses/apg/kosc-automated-problem-generation-app ) is not publicly available.

So it seems like I should modify the test scripts to add the flags for each personal challenge I make.

**Comment by danyk20** [comment]
Thank you for reporting this issue. I fixed it by making [generation library](https://github.com/danyk20/automated-problem-generation-lib) public with short demo (generating flags + uploading on CTFd server with personal challenge plugin). Since every use case requires specific adaptations, it's up to you how you are going to implement it. Feel free to contact me if you have any further questions.

**Comment by xihh87** [comment]
Thanks!
